version: '3'

services:
  vote:
    image: superkelly/vote:latest
    command: python app.py
    # volumes:
    #  - ./vote:/app
    ports:
      - '5000:80'
    networks:
      - front-tier
      - back-tier

  result:
    image: superkelly/result:latest
    command: nodemon server.js
    # volumes:
    #   - ./result:/app
    ports:
      - '5001:80'
      - '5858:5858'
    networks:
      - front-tier
      - back-tier

  worker:
    image: superkelly/worker:latest
    depends_on:
      - 'redis'
      - 'db'
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ['6379']
    networks:
      - back-tier

  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    container_name: db
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
